name: Deploy to RCade

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to RCade
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust WASM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          oevrride: true
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Build Trunk project
        run: trunk build --release
      - name: Deploy to RCade
        uses: fcjr/rcade/action-deploy@main
